# Notes
- Merge two dataframes by the FIPS
- Zillow csv problem: Some zillow files work in pd.read_csv(file) with no problem but if it doesn't work, try pd.read_csv(file, encoding="latin")

In [21]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [22]:
county_stats_1_file = "raw data/2018_all_county_data_1.csv"
stats_1_df = pd.read_csv(county_stats_1_file, encoding="latin")
stats_1_df.head(10)

,FIPS,State,County,% Fair/Poor,Physically Unhealthy Days,Mentally Unhealthy Days,% LBW,% Smokers,% Obese,Food Environment Index,...,20th Percentile Income,Income Ratio,# Single-Parent Households,# Households,% Single-Parent Households,# Households with Severe Problems,% Severe Housing Problems,% Drive Alone,% Long Commute - Drives Alone,Unnamed: 54
0,1001,Alabama,Autauga,18,4.2,4.3,9.0,19,36,7.1,...,23134.0,4.4,3368.0,13763.0,24.0,3090,15,87,41,NaN
1,1003,Alabama,Baldwin,18,4.1,4.2,8.0,17,29,7.9,...,22306.0,4.6,11348.0,43965.0,26.0,10455,14,85,40,NaN
2,1005,Alabama,Barbour,26,5.1,4.6,12.0,22,44,5.5,...,12650.0,5.9,3212.0,5705.0,56.0,1395,15,83,35,NaN
3,1007,Alabama,Bibb,20,4.4,4.3,11.0,20,38,7.6,...,18893.0,4.2,1479.0,4706.0,31.0,875,12,85,49,NaN
4,1009,Alabama,Blount,21,4.5,4.7,8.0,20,36,8.5,...,20634.0,4.1,3691.0,13523.0,27.0,2315,11,86,60,NaN
5,1011,Alabama,Bullock,29,5.2,4.8,15.0,23,40,4.5,...,10548.0,6.0,1632.0,2269.0,72.0,675,18,76,38,NaN
6,1013,Alabama,Butler,27,5.1,5.1,12.0,22,36,6.5,...,14452.0,5.1,2392.0,4699.0,51.0,1225,15,85,32,NaN
7,1015,Alabama,Calhoun,20,4.3,4.5,9.0,20,36,6.8,...,16952.0,4.9,9736.0,25367.0,38.0,6935,15,85,29,NaN
8,1017,Alabama,Chambers,25,5.0,4.9,12.0,22,38,6.1,...,15692.0,4.7,3423.0,7177.0,48.0,2560,18,88,33,NaN
9,1019,Alabama,Cherokee,19,4.3,4.7,9.0,19,36,8.2,...,17112.0,4.6,1694.0,5255.0,32.0,1850,16,85,46,NaN

In [23]:
top_20_ppsf_file= "Zillow CSV results/top_counties_ppsf_1.csv"
top_20_ppf_df=pd.read_csv(top_20_ppsf_file, encoding="latin")
top_20_ppf_df.head(10)

,Unnamed: 0,RegionName,State,StateCodeFIPS,MunicipalCodeFIPS,Month,Price per ft2,FIPS
0,51715,New York County,NY,36,61,2016-01,1873.989099,36061
1,81694,Nantucket County,MA,25,19,2017-02,1169.193935,25019
2,128808,Pitkin County,CO,8,97,2018-12,1152.469493,8097
3,116380,San Francisco County,CA,6,75,2018-07,1061.513031,6075
4,122858,San Mateo County,CA,6,81,2018-10,890.528228,6081
5,128654,Teton County,WY,56,39,2018-12,859.356161,56039
6,129160,San Miguel County,CO,8,113,2018-12,778.743316,8113
7,88320,Kings County,NY,36,47,2017-06,769.169231,36047
8,112024,Santa Clara County,CA,6,85,2018-05,712.178245,6085
9,81450,Dukes County,MA,25,7,2017-02,681.895803,25007

In [24]:
top_ppsf_merge1_df=pd.merge(top_20_ppf_df,stats_1_df,how='left', on=['FIPS'])
#top__ppsf_merge1_df.head()
#print(len(top_ppsf_merge1_df))

In [25]:
top_ppsf_merge1_df

,Unnamed: 0,RegionName,State_x,StateCodeFIPS,MunicipalCodeFIPS,Month,Price per ft2,FIPS,State_y,County,...,20th Percentile Income,Income Ratio,# Single-Parent Households,# Households,% Single-Parent Households,# Households with Severe Problems,% Severe Housing Problems,% Drive Alone,% Long Commute - Drives Alone,Unnamed: 54
0,51715,New York County,NY,36,61,2016-01,1873.989099,36061,New York,New York,...,21283.0,8.9,97288.0,236957.0,41.0,185855,25,6,65,NaN
1,81694,Nantucket County,MA,25,19,2017-02,1169.193935,25019,Massachusetts,Nantucket,...,44337.0,3.4,643.0,2131.0,30.0,845,21,66,4,NaN
2,128808,Pitkin County,CO,8,97,2018-12,1152.469493,8097,Colorado,Pitkin,...,36189.0,3.8,860.0,2824.0,30.0,1335,18,51,21,NaN
3,116380,San Francisco County,CA,6,75,2018-07,1061.513031,6075,California,San Francisco,...,26514.0,7.2,28646.0,113355.0,25.0,93130,27,35,50,NaN
4,122858,San Mateo County,CA,6,81,2018-10,890.528228,6081,California,San Mateo,...,41399.0,4.8,35467.0,161030.0,22.0,62170,24,69,38,NaN
5,128654,Teton County,WY,56,39,2018-12,859.356161,56039,Wyoming,Teton,...,37270.0,4.0,1157.0,4391.0,26.0,1445,18,64,12,NaN
6,129160,San Miguel County,CO,8,113,2018-12,778.743316,8113,Colorado,San Miguel,...,25451.0,4.1,369.0,1487.0,25.0,910,27,47,26,NaN
7,88320,Kings County,NY,36,47,2017-06,769.169231,36047,New York,Kings,...,17051.0,6.5,227305.0,602791.0,38.0,324280,35,18,57,NaN
8,112024,Santa Clara County,CA,6,85,2018-05,712.178245,6085,California,Santa Clara,...,39465.0,5.1,96243.0,432133.0,22.0,145855,24,76,38,NaN
9,81450,Dukes County,MA,25,7,2017-02,681.895803,25007,Massachusetts,Dukes,...,30057.0,4.3,1048.0,3089.0,34.0,1695,29,75,5,NaN
10,120877,Marin County,CA,6,41,2018-09,665.064362,6041,California,Marin,...,37367.0,5.7,11690.0,52789.0,22.0,25070,24,66,43,NaN
11,105624,Suffolk County,MA,25,25,2018-02,654.401742,25025,Massachusetts,Suffolk,...,16866.0,7.6,65587.0,130995.0,50.0,72725,25,41,48,NaN
12,104549,Summit County,UT,49,43,2018-01,645.947290,49043,Utah,Summit,...,41628.0,4.3,2060.0,10166.0,20.0,1940,14,75,39,NaN
13,127475,Maui County,HI,15,9,2018-12,642.164782,15009,Hawaii,Maui,...,29963.0,4.2,12629.0,36087.0,35.0,17115,32,72,27,NaN
14,106438,Eagle County,CO,8,37,2018-02,587.457129,8037,Colorado,Eagle,...,40478.0,3.5,2479.0,12075.0,21.0,3475,19,72,25,NaN
15,123519,Kauai County,HI,15,7,2018-10,576.119403,15007,Hawaii,Kauai,...,29446.0,4.1,4358.0,15599.0,28.0,5945,27,79,36,NaN
16,105587,Honolulu County,HI,15,3,2018-02,570.927901,15003,Hawaii,Honolulu,...,34849.0,4.0,56221.0,211045.0,27.0,84780,27,64,44,NaN
17,86314,Santa Barbara County,CA,6,83,2017-05,563.175200,6083,California,Santa Barbara,...,27231.0,4.8,30669.0,97936.0,31.0,42255,30,68,18,NaN
18,116563,Santa Cruz County,CA,6,87,2018-07,561.782662,6087,California,Santa Cruz,...,27103.0,5.3,15585.0,53771.0,29.0,25710,27,69,38,NaN
19,114265,District of Columbia,DC,11,1,2018-06,554.312115,11001,District of Columbia,District of Columbia,...,22466.0,7.2,61573.0,113461.0,54.0,57660,22,34,46,NaN

In [26]:
bottom_20_ppsf_file= "Zillow CSV results/bottom_counties_ppsf_1.csv"
bottom_20_ppsf_df=pd.read_csv(bottom_20_ppsf_file, encoding="latin")
bottom_20_ppsf_df.head()

,Unnamed: 0,RegionName,State,StateCodeFIPS,MunicipalCodeFIPS,Month,Price per ft2,FIPS
0,124277,Monroe County,AL,1,99,2018-10,26.421191,1099
1,103349,Haskell County,TX,48,207,2017-12,31.245572,48207
2,126958,Mitchell County,TX,48,335,2018-11,33.310902,48335
3,126405,Wyoming County,WV,54,109,2018-11,34.151151,54109
4,96459,Jackson County,AR,5,67,2017-09,36.000000,5067

In [27]:
bottom_ppsf_merge1_df=pd.merge(bottom_20_ppf_df,stats_1_df,how='left', on=['FIPS'])
bottom_ppsf_merge1_df

,Unnamed: 0,RegionName,State_x,StateCodeFIPS,MunicipalCodeFIPS,Month,Price per ft2,FIPS,State_y,County,...,20th Percentile Income,Income Ratio,# Single-Parent Households,# Households,% Single-Parent Households,# Households with Severe Problems,% Severe Housing Problems,% Drive Alone,% Long Commute - Drives Alone,Unnamed: 54
0,124277,Monroe County,AL,1,99,2018-10,26.421191,1099,Alabama,Monroe,...,7581.0,8.8,2678.0,5146.0,52.0,1185,14,91,32,NaN
1,103349,Haskell County,TX,48,207,2017-12,31.245572,48207,Texas,Haskell,...,16710.0,4.3,401.0,871.0,46.0,270,12,81,12,NaN
2,126958,Mitchell County,TX,48,335,2018-11,33.310902,48335,Texas,Mitchell,...,26420.0,3.7,664.0,1678.0,40.0,190,7,82,31,NaN
3,126405,Wyoming County,WV,54,109,2018-11,34.151151,54109,West Virginia,Wyoming,...,15791.0,5.0,1471.0,4774.0,31.0,935,10,81,44,NaN
4,96459,Jackson County,AR,5,67,2017-09,36.000000,5067,Arkansas,Jackson,...,12952.0,5.2,1624.0,3505.0,46.0,835,13,86,24,NaN
5,100983,Morris County,TX,48,343,2017-11,36.543052,48343,Texas,Morris,...,17000.0,4.7,800.0,2877.0,28.0,655,13,87,32,NaN
6,105082,Falls County,TX,48,145,2018-01,37.259328,48145,Texas,Falls,...,13867.0,5.5,1549.0,3682.0,42.0,885,16,78,47,NaN
7,79097,Labette County,KS,20,99,2017-01,37.562604,20099,Kansas,Labette,...,18003.0,4.5,1670.0,4884.0,34.0,1170,14,84,17,NaN
8,100617,Hutchinson County,TX,48,233,2017-11,38.312274,48233,Texas,Hutchinson,...,19742.0,5.1,2065.0,5704.0,36.0,935,11,86,18,NaN
9,25090,Randolph County,IN,18,135,2014-12,39.819440,18135,Indiana,Randolph,...,19091.0,4.1,2293.0,5923.0,39.0,1200,11,83,33,NaN
10,122726,Greer County,OK,40,55,2018-09,40.031286,40055,Oklahoma,Greer,...,17550.0,4.2,448.0,1169.0,38.0,210,10,85,34,NaN
11,128266,Montgomery County,KS,20,125,2018-12,40.367989,20125,Kansas,Montgomery,...,16738.0,4.9,2996.0,7909.0,38.0,2190,16,81,17,NaN
12,60165,Brown County,KS,20,13,2016-04,40.808868,20013,Kansas,Brown,...,20450.0,3.8,758.0,2452.0,31.0,480,12,81,17,NaN
13,31911,Telfair County,GA,13,271,2015-03,40.911331,13271,Georgia,Telfair,...,12842.0,4.2,1436.0,2932.0,49.0,865,16,86,25,NaN
14,33574,Dunklin County,MO,29,69,2015-04,41.179056,29069,Missouri,Dunklin,...,12556.0,5.3,3662.0,8027.0,46.0,1750,14,84,28,NaN
15,80801,Cass County,IN,18,17,2017-02,41.957978,18017,Indiana,Cass,...,21649.0,3.6,3034.0,8955.0,34.0,2050,14,84,22,NaN
16,23414,Cass County,IL,17,17,2014-11,42.115609,17017,Illinois,Cass,...,22441.0,4.0,1153.0,3179.0,36.0,570,11,79,28,NaN
17,129104,Stephens County,TX,48,429,2018-12,42.369289,48429,Texas,Stephens,...,17758.0,5.0,701.0,2202.0,32.0,440,13,79,14,NaN
18,85561,Cherokee County,KS,20,21,2017-04,42.647059,20021,Kansas,Cherokee,...,19358.0,4.0,1228.0,4955.0,25.0,935,12,86,24,NaN
19,59962,Nolan County,TX,48,353,2016-04,42.649098,48353,Texas,Nolan,...,17513.0,4.7,1640.0,3710.0,44.0,570,10,85,15,NaN

In [28]:
county_stats_2_file = "raw data/2018_all_county_data_2.csv"
stats_2_df = pd.read_csv(county_stats_2_file, encoding="latin")
stats_2_df.head()

,FIPS,State,County,# Deaths,Age-Adjusted Mortality,# Deaths.1,Child Mortality Rate,# Deaths.2,Infant Mortality Rate,% Frequent Physical Distress,...,# Non-Hispanic White,% Non-Hispanic White,# Not Proficient in English,% Not Proficient in English,95% CI - Low,95% CI - High,% Female,# Rural,% Rural,Unnamed: 56
0,1001,Alabama,Autauga,827.0,450.0,31.0,56.2,34.0,8.0,13,...,41562,75.0,432,0.8,0.5,1.2,51.3,22921.0,42.0,NaN
1,1003,Alabama,Baldwin,2753.0,351.0,85.0,47.7,85.0,6.0,13,...,173529,83.2,1540,0.8,0.5,1.1,51.5,77060.0,42.3,NaN
2,1005,Alabama,Barbour,418.0,434.0,15.0,66.6,NaN,NaN,16,...,12061,46.5,382,1.5,0.8,2.2,46.9,18613.0,67.8,NaN
3,1007,Alabama,Bibb,408.0,529.0,22.0,116.3,25.0,15.0,13,...,16850,74.4,96,0.4,0.0,1.0,46.4,15663.0,68.4,NaN
4,1009,Alabama,Blount,996.0,480.0,30.0,55.4,25.0,5.0,14,...,50472,87.5,1018,1.9,1.3,2.4,50.6,51562.0,90.0,NaN

In [29]:
top_ppsf_merge2_df=pd.merge(top_20_ppf_df,stats_2_df,how='left', on=['FIPS'])
top_ppsf_merge2_df

,Unnamed: 0,RegionName,State_x,StateCodeFIPS,MunicipalCodeFIPS,Month,Price per ft2,FIPS,State_y,County,...,# Non-Hispanic White,% Non-Hispanic White,# Not Proficient in English,% Not Proficient in English,95% CI - Low,95% CI - High,% Female,# Rural,% Rural,Unnamed: 56
0,51715,New York County,NY,36,61,2016-01,1873.989099,36061,New York,New York,...,771611,46.9,144635,9.3,9.0,9.6,52.6,0.0,0.0,NaN
1,81694,Nantucket County,MA,25,19,2017-02,1169.193935,25019,Massachusetts,Nantucket,...,8196,74.5,300,3.0,1.2,4.7,49.4,1922.0,18.9,NaN
2,128808,Pitkin County,CO,8,97,2018-12,1152.469493,8097,Colorado,Pitkin,...,15270,86.0,150,0.9,0.1,1.7,47.7,7580.0,44.2,NaN
3,116380,San Francisco County,CA,6,75,2018-07,1061.513031,6075,California,San Francisco,...,356530,40.9,100414,12.4,12.0,12.7,49.1,0.0,0.0,NaN
4,122858,San Mateo County,CA,6,81,2018-10,890.528228,6081,California,San Mateo,...,304305,39.8,57020,8.0,NaN,NaN,50.7,13586.0,1.9,NaN
5,128654,Teton County,WY,56,39,2018-12,859.356161,56039,Wyoming,Teton,...,18896,81.5,776,3.6,2.1,5.1,48.4,9887.0,46.4,NaN
6,129160,San Miguel County,CO,8,113,2018-12,778.743316,8113,Colorado,San Miguel,...,6889,85.9,45,0.6,0.0,1.6,46.5,7359.0,100.0,NaN
7,88320,Kings County,NY,36,47,2017-06,769.169231,36047,New York,Kings,...,947170,36.0,302816,12.5,12.4,12.7,52.6,37.0,0.0,NaN
8,112024,Santa Clara County,CA,6,85,2018-05,712.178245,6085,California,Santa Clara,...,620294,32.3,171519,9.7,NaN,NaN,49.5,19307.0,1.1,NaN
9,81450,Dukes County,MA,25,7,2017-02,681.895803,25007,Massachusetts,Dukes,...,15074,87.4,404,2.5,0.5,4.5,50.9,6453.0,39.0,NaN
10,120877,Marin County,CA,6,41,2018-09,665.064362,6041,California,Marin,...,187316,71.9,10590,4.3,3.9,4.7,51.2,16457.0,6.5,NaN
11,105624,Suffolk County,MA,25,25,2018-02,654.401742,25025,Massachusetts,Suffolk,...,359494,45.8,76334,10.5,10.2,10.9,51.6,535.0,0.1,NaN
12,104549,Summit County,UT,49,43,2018-01,645.947290,49043,Utah,Summit,...,34148,84.7,974,2.7,2.0,3.3,48.9,14239.0,39.2,NaN
13,127475,Maui County,HI,15,9,2018-12,642.164782,15009,Hawaii,Maui,...,50378,30.5,4798,3.2,2.6,3.7,50.1,22556.0,14.6,NaN
14,106438,Eagle County,CO,8,37,2018-02,587.457129,8037,Colorado,Eagle,...,36251,67.1,3228,6.5,5.3,7.7,46.9,10431.0,20.0,NaN
15,123519,Kauai County,HI,15,7,2018-10,576.119403,15007,Hawaii,Kauai,...,21339,29.6,2329,3.5,2.8,4.3,50.2,8628.0,12.9,NaN
16,105587,Honolulu County,HI,15,3,2018-02,570.927901,15003,Hawaii,Honolulu,...,184324,18.6,51617,5.6,NaN,NaN,49.6,8225.0,0.9,NaN
17,86314,Santa Barbara County,CA,6,83,2017-05,563.175200,6083,California,Santa Barbara,...,200747,45.0,45946,11.2,10.7,11.7,50.0,21269.0,5.0,NaN
18,116563,Santa Cruz County,CA,6,87,2018-07,561.782662,6087,California,Santa Cruz,...,158522,57.7,20762,8.1,7.5,8.7,50.5,31589.0,12.0,NaN
19,114265,District of Columbia,DC,11,1,2018-06,554.312115,11001,District of Columbia,District of Columbia,...,248169,36.4,14878,2.4,2.2,2.6,52.5,0.0,0.0,NaN

In [19]:
bottom_ppsf_merge2_df=pd.merge(bottom_20_ppf_df,stats_2_df,how='left', on=['FIPS'])
bottom_ppsf_merge2_df

,Unnamed: 0,RegionName,State_x,StateCodeFIPS,MunicipalCodeFIPS,Month,Price per ft2,FIPS,State_y,County,...,# Non-Hispanic White,% Non-Hispanic White,# Not Proficient in English,% Not Proficient in English,95% CI - Low,95% CI - High,% Female,# Rural,% Rural,Unnamed: 56
0,124277,Monroe County,AL,1,99,2018-10,26.421191,1099,Alabama,Monroe,...,11772,54.7,18,0.1,0.0,0.6,52.3,18234.0,79.0,NaN
1,103349,Haskell County,TX,48,207,2017-12,31.245572,48207,Texas,Haskell,...,3661,64.4,653,11.6,7.9,15.3,47.2,2809.0,47.6,NaN
2,126958,Mitchell County,TX,48,335,2018-11,33.310902,48335,Texas,Mitchell,...,4182,48.0,404,4.7,2.5,6.9,40.1,3455.0,36.7,NaN
3,126405,Wyoming County,WV,54,109,2018-11,34.151151,54109,West Virginia,Wyoming,...,21167,97.3,7,0.0,0.0,0.5,50.7,21151.0,88.9,NaN
4,96459,Jackson County,AR,5,67,2017-09,36.000000,5067,Arkansas,Jackson,...,13239,76.9,33,0.2,0.0,0.8,50.5,11709.0,65.1,NaN
5,100983,Morris County,TX,48,343,2017-11,36.543052,48343,Texas,Morris,...,8170,64.9,240,2.0,NaN,NaN,52.1,10143.0,78.4,NaN
6,105082,Falls County,TX,48,145,2018-01,37.259328,48145,Texas,Falls,...,8819,51.1,549,3.4,2.1,4.7,52.4,12034.0,67.4,NaN
7,79097,Labette County,KS,20,99,2017-01,37.562604,20099,Kansas,Labette,...,17459,85.4,121,0.6,0.0,1.2,50.5,11309.0,52.3,NaN
8,100617,Hutchinson County,TX,48,233,2017-11,38.312274,48233,Texas,Hutchinson,...,15190,70.6,458,2.3,1.2,3.3,49.6,4998.0,22.6,NaN
9,25090,Randolph County,IN,18,135,2014-12,39.819440,18135,Indiana,Randolph,...,23667,94.4,183,0.8,0.0,1.5,50.9,16191.0,61.9,NaN
10,122726,Greer County,OK,40,55,2018-09,40.031286,40055,Oklahoma,Greer,...,4495,74.9,9,0.2,0.0,1.2,42.8,3285.0,52.7,NaN
11,128266,Montgomery County,KS,20,125,2018-12,40.367989,20125,Kansas,Montgomery,...,26144,79.8,365,1.2,0.6,1.8,50.7,15403.0,43.4,NaN
12,60165,Brown County,KS,20,13,2016-04,40.808868,20013,Kansas,Brown,...,8075,83.4,22,0.2,0.0,0.9,51.1,6833.0,68.4,NaN
13,31911,Telfair County,GA,13,271,2015-03,40.911331,13271,Georgia,Telfair,...,7861,49.2,1087,6.9,5.4,8.5,41.5,7753.0,47.0,NaN
14,33574,Dunklin County,MO,29,69,2015-04,41.179056,29069,Missouri,Dunklin,...,24795,81.2,410,1.4,0.9,1.9,52.1,16122.0,50.5,NaN
15,80801,Cass County,IN,18,17,2017-02,41.957978,18017,Indiana,Cass,...,30504,80.4,1795,5.0,3.9,6.1,49.8,17405.0,44.7,NaN
16,23414,Cass County,IL,17,17,2014-11,42.115609,17017,Illinois,Cass,...,9680,76.4,699,5.7,4.2,7.2,49.5,7112.0,52.1,NaN
17,129104,Stephens County,TX,48,429,2018-12,42.369289,48429,Texas,Stephens,...,6997,70.6,341,3.7,1.8,5.6,45.3,3791.0,39.4,NaN
18,85561,Cherokee County,KS,20,21,2017-04,42.647059,20021,Kansas,Cherokee,...,17870,88.3,22,0.1,0.0,0.6,50.2,10599.0,49.1,NaN
19,59962,Nolan County,TX,48,353,2016-04,42.649098,48353,Texas,Nolan,...,8448,56.3,311,2.2,1.3,3.2,50.3,4969.0,32.7,NaN